OnlineClassManagement/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineClassManagement.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin

        public ActionResult ContactUs()
        {
            return View();
        }



        public ActionResult AddCourseCategory()
        {
            return View();
        }


        public ActionResult CourseCategory()
        {
            return View();
        }


        public ActionResult CourseIndex()
        {
            return View();
        }

        public ActionResult InstructorIndex()
        {
            return View();
        }



        public ActionResult InstructorProfileIndex()
        {
            return View();
        }


        public ActionResult StudentIndex()
        {
            return View();
        }



        public ActionResult StudentProfile()
        {
            return View();
        }


        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }



    }
}

OnlineClassManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repositary;
namespace OnlineClassManagement.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult AdminSignup()
        {
            return View();
        }
        public ActionResult InstructorSignup()
        {
            return View();
        }


        public ActionResult StudentSignup()
        {
            return View();
        }
        public ActionResult FinanceContent()
        {
            return View();
        }
        public ActionResult AspMvcContent()
        {
            return View();
        }
        public ActionResult AdobeIllustratorContent()
        {
            return View();
        }
        public ActionResult AccountingContent()
        {
            return View();
        }
        public ActionResult DataScienceContent()
        {
            return View();
        }
        public ActionResult BackEndContent()
        {
            return View();
        }
        public ActionResult FrontEndContent()
        {
            return View();
        }
        public ActionResult ArtificialIntelligenceContent()
        {
            return View();
        }
        public ActionResult AdobePhotoShopContent()
        {
            return View();
        }
        public ActionResult DigitalMarketingContent()
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
        public ActionResult AccountingDetails()
        {
            return View();
        }
        public ActionResult ArtificialIntelligenceDetails()
        {
            return View();
        }
        public ActionResult DataScienceDetails()
        {
            return View();
        }
        public ActionResult BackendDvevlopmentDetails()
        {
            return View();
        }
        public ActionResult FrontendManagementDetails()
        {
            return View();
        }
        public ActionResult AdobePhotoShopDetails()
        {
            return View();
        }
        public ActionResult AdobeIllusatorDetails()
        {
            return View();
        }
        public ActionResult FinanceManagementDetails()
        {
            return View();
        }
        public ActionResult DigitalMarketingDetails()
        {
            return View();
        }
        public ActionResult EthicalHackingDetails()
        {
            return View();
        }
        public ActionResult Designing()
        {
            return View();
        }
        public ActionResult Developing()
        {
            return View();
        }
        public ActionResult Business()
        {
            return View();
        }
        public ActionResult ASPMVCfullVideo()
        {
            return View();
        }
        public ActionResult ASPMVCVideo()
        {
            return View();
        }

        public ActionResult ASPMVCDetails()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Mycourse()
        {
            return View();
        }
        public ActionResult CourseCertificate()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult CorelDrawfullVideo()
        {
            return View();
        }
        public ActionResult CorelDrawVideo()
        {
            return View();
        }
        public ActionResult Signup()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cart()
        {
            return View();
        }

        public ActionResult SecondPageProduct()
        {
            return View();
        }

        public ActionResult Product()
        {
            return View();
        }
        public ActionResult ProductDetails()
        {
            return View();
        }

        public ActionResult demo()
        {
            return View();
        }
    }
}

OnlineClassManagement/Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineClassManagement.Controllers
{
    public class InstructorController : Controller
    {
        // GET: Instructor
        public ActionResult Student()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashbord()
        {
            return View();
        }
        public ActionResult NewCourse()
        {
            return View();
        }

        public ActionResult AllCourse()
        {
            return View();

        }
        public ActionResult Message()
        {
            return View();
        }
        public ActionResult Comment()
        {
            return View();
        }
        public ActionResult QuizCreate()
        {
            return View();
        }

        public ActionResult QuizList()
        {
            return View();
        }
        public ActionResult Myprofile()
        {
            return View();
        }




    } 
}

OnlineClassManagement/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineClassManagement.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Notification()
        {
            return View();
        }
        public ActionResult Profile()
        {
            return View();
        }
        public ActionResult Message()
        {
            return View();
        }
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

OnlineClassManagement/Views/Admin/AddCourseCategory.cshtml
@{
    ViewBag.Title = "AddCourseCategory";
    Layout = "~/Views/Shared/_Admin.cshtml";
}



<style>
    .MainDiv {
        margin: -100px -100px;
    }

    .SubmitButton {
        background-color: black; /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 10px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
        border-radius: 8px;
        margin-bottom: -10px;
    }

        .SubmitButton:hover {
            background-color: #555555;
            color: white;
        }
</style>

<div class="MainDiv">
    <h2>Add Course Category</h2>
    <div style="background-color:gray;padding:30px 20px;border-radius:8px;">
        <form action="/action_page.php">
            <label for="fullName">Choose Thumbnail</label>
            <input type="file" id="" name="myfile"><br><br>
            <label for="fullName">Category Name</label>
            <input type="text" class="form-control" id="CategoryName" placeholder="Enter Category name">
            <label for="fullName">Description</label>
            <input type="text" class="form-control" id="Description" placeholder="Enter Description">
            <button class="SubmitButton">Submit</button>
        </form>
    </div>
</div>

OnlineClassManagement/Views/Admin/ContactUs.cshtml
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/_Admin.cshtml";
}



<link rel="stylesheet" href="~/Content/css/ContactUs.css">


<div class="mainDiv" style="margin-top:100px;">
    <h3> Hello</h3>
    <div class="container">
        <form action="action_page.php" style="color:white">

            <label for="fname">Your Name</label>
            <input type="text" id="fname" name="firstname" placeholder="Your name..">

            <label for="lname">Email Address</label>
            <input type="text" id="lname" name="lastname" placeholder="Email">

            @*<label for="country">Country</label>
                <select id="country" name="country">
                    <option value="australia">Australia</option>
                    <option value="canada">Canada</option>
                    <option value="usa">USA</option>
                </select>*@

            <label for="subject">Subject</label>
            <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

            <input type="submit" value="Submit">

        </form>
    </div>

</div>

OnlineClassManagement/Views/Admin/CourseCategory.cshtml
@{
    ViewBag.Title = "CourseCategory";
    Layout = "~/Views/Shared/_Admin.cshtml";
}



<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        margin: auto;
        text-align: center;
        font-family: arial;
        margin: 20px;
        width: 200px;
    }

    .price {
        color: grey;
        font-size: 22px;
    }

    .card button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

        .card button:hover {
            opacity: 0.7;
        }

    .text {
        font-size: 15px;
        font-weight: 500;
        margin-top: 80px;
        margin-left: 33px;
    }

    .button {
        border-radius: 8px;
    }

    .button {
        display: inline-block;
        border-radius: 4px;
        background-color: black;
        border: none;
        color: #FFFFFF;
        text-align: center;
        font-size: 28px;
        padding: 10px;
        width: 100%;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
        vertical-align: middle;
    }

        .button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

            .button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
            }

        .button:hover span {
            padding-right: 25px;
        }

            .button:hover span:after {
                opacity: 1;
                right: 0;
</style>


<body style="margin-top:50px;">

    <h2 style="text-align:center">Course Category</h2>

    <div style="display:flex;">
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Photoshop</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Video Lecture</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Dotnet</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Java</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
    </div>

    <div style="display:flex;">
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p><button class="button">View All</button></p>
        </div>
    </div>

    <button class="button"><span><a href="/Admin/AddCourseCategory">New Category </a> </span></button>
</body>

OnlineClassManagement/Views/Admin/CourseIndex.cshtml
@{
    ViewBag.Title = "CourseIndex";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
@*Course Index*@


    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
            margin: 20px;
        }

        .price {
            color: grey;
            font-size: 22px;
        }

        .card button {
            border: none;
            outline: 0;
            padding: 12px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

            .card button:hover {
                opacity: 0.7;
            }

        .text {
            font-size: 15px;
            font-weight: 500;
            margin-top: 80px;
            margin-left: 33px;
        }

        .button {
            border-radius: 8px;
        }
    </style>
}

<body style="margin-top:50px;">

    <h2 style="text-align:center">Course List</h2>

    <div style="display:flex;">
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$19.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$29.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$39.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$59.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$9.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
    </div>

    <div style="display:flex;">
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$19.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$29.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$39.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$59.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
        <div class="card">
            <img src="~/Content/Images/adobe.jpg" alt="Denim Jeans" style="width:100%">
            <h3>Adobe Course</h3>
            <p class="price">$9.99</p>
            <p>Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum.</p>
            <p><button class="button">View Course Details</button></p>
        </div>
    </div>
</body>

OnlineClassManagement/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

OnlineClassManagement/Views/Admin/StudentProfile.cshtml
@{
    ViewBag.Title = "StudentProfile";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

OnlineClassManagement/Views/Home/ASPMVCVideo.cshtml
@{
    ViewBag.Title = "ASPMVCVideo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h2>ASP.NET MVC Video</h2>
    <hr />
    <iframe width="100%" height="600" src="https://www.youtube.com/embed/tgbNymZ7vqY?controls=0">
    </iframe>

    <br />
    <br />
    <p>
        CorelDraw is one of the most popular graphics designing software available in market.
        This amazing designing Software meet the day-to-day demands of working designers.
        It is designed to edit two-dimensional images such as logos, posters etc.
        CorelDraw Graphics Suite software is available in the market and once installed in the computer,
        you can get easily start with your graphic designing work.
        There are lots of benefits of CorelDraw for Business as Corel draw is what you ask for,
        right from creating simple shapes and lines to complex ones which are used to create illustrations,
        clipart, logos etc.

        CorelDRAW Graphics Suite 2020,
        the newest and most innovative product from Corel,
        which includes all the top-rated & latest tools found in CorelDRAW Graphics Suite X8 and much more.
        Now you  can design with the latest technology, including advanced support for Microsoft Windows 10,
        Windows 8.1 and 7 along with multi-monitor viewing,
        4K displays & touch-device enhancements and much more.
        This latest graphics suite 2018 provides everything you need to deliver professional designing results with speed and confidence.
        You can buy CorelDRAW Graphics Suite 2020 license from CorelDraw Reseller India – Wroffy Technologies.
    </p>


    <div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                50%
            </div>
        </div>
    </div>

    <br>

    <button type="button" class="btn btn-secondary btn-lg">@Html.ActionLink("Next", "ASPMVCfullVideo", "Home")</button>

</body>
</html>

OnlineClassManagement/Views/Home/ASPMVCfullVideo.cshtml
@{
    ViewBag.Title = "ASPMVCfullVideo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ASPMVCfullVideo</h2>


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <h2>Asp.net mvc video</h2>
    <hr />
    <iframe width="1000" height="600" src="https://www.youtube.com/embed/tgbNymZ7vqY?controls=0">
    </iframe>

    <br />
    <br />
    <p>
        CorelDraw is one of the most popular graphics designing software available in market.
        This amazing designing Software meet the day-to-day demands of working designers.
        It is designed to edit two-dimensional images such as logos, posters etc.
        CorelDraw Graphics Suite software is available in the market and once installed in the computer,
        you can get easily start with your graphic designing work.
        There are lots of benefits of CorelDraw for Business as Corel draw is what you ask for,
        right from creating simple shapes and lines to complex ones which are used to create illustrations,
        clipart, logos etc.

        CorelDRAW Graphics Suite 2020,
        the newest and most innovative product from Corel,
        which includes all the top-rated & latest tools found in CorelDRAW Graphics Suite X8 and much more.
        Now you  can design with the latest technology, including advanced support for Microsoft Windows 10,
        Windows 8.1 and 7 along with multi-monitor viewing,
        4K displays & touch-device enhancements and much more.
        This latest graphics suite 2018 provides everything you need to deliver professional designing results with speed and confidence.
        You can buy CorelDRAW Graphics Suite 2020 license from CorelDraw Reseller India – Wroffy Technologies.
    </p>


    <div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="100" aria-valuemax="100" style="width:100%">

            </div>
        </div>
    </div>

    <br>

    <button type="button" class="btn btn-Secondary btn-lg">@Html.ActionLink("Complete", "CourseCertificate", "Home")</button>

</body>
</html>

OnlineClassManagement/Views/Home/CourseCertificate.cshtml
@{
    ViewBag.Title = "CourseCertificate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<hr/>
<h2>CourseCertificate</h2>

 <br/>
<br/>
<br/>

<div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
    <div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
        <h2 style="text-align:center"> LearninGo</h2><br />
        <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
        <br><br>
        <span style="font-size:25px"><i>This is to certify that</i></span>
        <br><br>
        <span style="font-size:30px"><b>$student.getFullName()</b></span><br /><br />
        <span style="font-size:25px"><i>has completed the course</i></span> <br /><br />
        <span style="font-size:30px">Corel Draw</span> <br /><br />
        <br /><br /><br /><br />
        <span style="font-size:25px"><i>dated</i></span><br>
        <p id="date"></p>
        <script>
document.getElementById("date").innerHTML = Date();
        </script>
       <!-- #set ($dt = $DateFormatter.getFormattedDate($grade.getAwardDate(), "MMMM dd, yyyy"))
        <span style="font-size:30px"></span> -->
    </div>
</div>

OnlineClassManagement/Views/Shared/_Instructor.cshtml
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
<link href="~/Content/css/main.css" rel="stylesheet" />
<link href="~/Content/css/style (1).css" rel="stylesheet" />
<link href="~/Content/css/util.css" rel="stylesheet" />
<script src="~/Content/js/main.js"></script>

<script src="~/Content/js/main2.js"></script>

    <meta charset="utf-8">

    <title>Sidebar Dashboard Template With Sub Menu</title>

    <link rel="stylesheet" href="style.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">

        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />

    </svg>

    <link href="~/Content/css/style.css" rel="stylesheet" />

    <style>

        .main-container {
        }
    </style>





    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>

</head>

<body style="margin-left:-10px">



    <!--wrapper start-->

    <div class="wrapper">

        <!--header menu start-->

        <div class="header">

            <div class="header-menu">

                <div class="title">Coding <span>Snow</span></div>

                <div class="sidebar-btn">

                    <i class="fas fa-bars"></i>

                </div>

                <ul>

                    <li><a href="#"><i class="fas fa-search"></i></a></li>

                    <li><a href="#"><i class="fas fa-bell"></i></a></li>

                    <li><a href="/Home/Index"><i class="fas fa-power-off"></i></a></li>

                </ul>

            </div>

        </div>

        <!--header menu end-->
        <!--sidebar start-->

        <div class="sidebar">

            <div class="sidebar-menu">

                <center class="profile">

                    <img src="~/Content/images/ETH.jpg" alt="">

                    <p><a href="@Url.Action("MyProfile","Instructor")" style="color:white">Nitesh</a></p>

                </center>

                <li class="item">

                    <a href="@Url.Action("Dashbord","Instructor")" class="menu-btn">

                        <i class="fas fa-desktop"></i><span>Dashboard</span>

                    </a>

                </li>

                <li class="item" id="course">

                    <a href="#course" class="menu-btn">

                        <i class="" bi bi-book"></i><span>Courses <i class="fas fa-chevron-down drop-down"></i></span>

                    </a>

                    <div class="sub-menu">

                        <a href="@Url.Action("NewCourse","Instructor")"><i class="fas fa-image"></i><span>Start New Course</span></a>

                        <a href="@Url.Action("AllCourse","Instructor")"><i class="fas fa-address-card"></i><span>All Courses</span></a>

                    </div>

                </li>

                <li class="item" id="message">

                    <a href="#message" class="menu-btn">

                        <i class="fas fa-sms"></i><span>messages <i class="fas fa-chevron-down drop-down"></i></span>

                    </a>

                    <div class="sub-menu">

                        <a href="@Url.Action("Message","Instructor")"><i class="fas fa-comment-alt"></i><span>Message</span></a>

                        <a href="@Url.Action("Comment","Instructor")"><i class="fas fa-comment"></i><span>Comment</span></a>

                    </div>

                </li>

                <li class="item" id="settings">

                    <a href="#settings" class="menu-btn">

                        <i class="fas fa-cog"></i><span>Quiz<i class="fas fa-chevron-down drop-down"></i></span>

                    </a>

                    <div class="sub-menu">

                        <a href="@Url.Action("QuizCreate","Instructor")"><i class="fas fa-lock"></i><span>Quiz Create</span></a>

                        <a href="@Url.Action("QuizList","Instructor")"><i class="fas fa-language"></i><span>Quiz List</span></a>

                    </div>

                </li>

                <li class="item">

                    <a href="@Url.Action("Student","Instructor")" class="menu-btn">

                        <i class="fas fa-user-alt"></i><span>Student</span>

                    </a>

                </li>

            </div>

        </div>

        <!--sidebar end-->
        <!--main container start-->

        <div class="main-container">



            @RenderBody();





        </div>

        <!--main container end-->

    </div>

    <!--wrapper end-->



    <script type="text/javascript">

        $(document).ready(function () {

            $(".sidebar-btn").click(function () {

                $(".wrapper").toggleClass("collapse");

            });

        });

    </script>



</body>

</html>